### ISSUE TITLE
UI is not adaptive for different screen sizes

### ISSUE THREAD

**Issue by N02870941** [N02870941/calculator-ios#1]
**Describe the bug**

The UI is setup for iPhone SE resolution (1136 x 640) and the buttons do not expand to take up the full screen for any other screen size. For smaller phones such as the iPhone 4, not all buttons are on screen.

Each button (except for 0) takes up 77x77 pixels (77 is roughly 1/4) of the screen width of iPhone SE. Instead, how can we go from fixed size to proportions?

**To Reproduce**
1. Follow install instructions from README.md and run the app in simulator on a screen size other than that of iPhone SE

**Expected behavior**
For larger screen formats the app only takes up 1136 x 640 pixels, and the rest of the screen is blank.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by N02870941** [comment]
@sheinix If can you, please submit a PR. I am having trouble getting that to work. I would greatly greatly appreciate it!

**Comment by sheinix** [comment]
Hi @N02870941 no problem. Does the repository has writing permissions for developers?

**Comment by N02870941** [comment]
@sheinix I'm not sure. I just unchecked a checkbox that says something like "Only allow collaborators to edit". How do I make it so that you can fork and make a pull request. I've actually never set that up myself before haha. I appreciate your help again

**Comment by sheinix** [comment]
Hi @N02870941 

Go to Repository > Settings > Collaborators
You will see a text box with a Add button. In order to add a collaborator you start typing in the text box until you see the actual username suggested to you in the drop down list that appears as you type.
Select that username which will cause a green check mark to appear indicating the system recognized that username.
Press Add to add that collaborator to the repository
